### ISSUE TITLE
Hello, Master About version 0.3 automatic phishing, which is unavailable due to the game update

### ISSUE THREAD

**Issue by JerryTaoo** [Greetlist/wow_fishing_script#1]
Hello, Master
    I'm a CN player,Have the honor to use your development。
    Beijing Time 2022.12.7,The software is no longer working properly,I hope you can continue to update the new version。
    Thank you very much！

**Comment by Greetlist** [comment]
OK, I will test it after work. By the way, find a little ```dark``` environment to try it again.

**Comment by Greetlist** [comment]
I test it in real game, and it works fine.Did you forget to set the MaxFishingCount config? ⚠️ **(MaxFishingCount == 0) is not infinity**

**Comment by JerryTaoo** [comment]
Thanks again for your reply，It may be the problem caused by my choice of fishing site，The English option in the software is also one of the difficulties，I can't understand the correct meaning of the option，Thank you for your development，excellent！
