### ISSUE TITLE
Debug HSV Color Range步骤遇到的问题

### ISSUE THREAD

**Issue by Zzealot1** [Greetlist/wow_fishing_script#3]
选择鱼漂范围后，在校准颜色部分，没法使用Q退出，并且在点击X退出后程序进入未响应状态，有可能是因为没有完成颜色校准，但是还请帮助解决颜色校准部分的问题

**Comment by Greetlist** [comment]
进入校准颜色对话框之后，默认的输入法会跳转回中文，需要再手动切换回英文输入法之后再按q退出，小写`q`即可,不要大写.

**Comment by Greetlist** [comment]
@Zzealot1 能用吗？能用的话我就把Issue关了。

**Comment by Zzealot1** [comment]
好了谢谢请关闭
