### ISSUE TITLE
cv2.error: OpenCV(4.10.0)

### ISSUE THREAD

**Issue by micenote** [Greetlist/wow_fishing_script#5]
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:315: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'

**Comment by micenote** [comment]
还有在4k显示器下，缩放200%。截图有问题。

**Comment by Greetlist** [comment]
把出问题的截图和截图坐标发给我吧，我看看

**Comment by micenote** [comment]
> 把出问题的截图和截图坐标发给我吧，我看看

这个问题还挺复杂。我直接改成1920*1080的分辩率了。

你这钓鱼的快捷键是“1”吗？
点一次开始就运行一次，然后也不捡鱼，然后就不动了。

**Comment by Greetlist** [comment]
1920*1080分辨率可以用是吗？那可能是截图的时候没有按照分辨率来调整坐标，我猜。
你按照这个步骤再试试：
1. 把钓鱼放在1
2. 执行这两个宏
```
/console SoftTargetInteractArc 2      # allowed you to interact without facing things
/console SoftTargetInteractRange 50   # increase your interact range to 50
```
3. 把镜头调成第一人称那种样子
4. 框选钓鱼的水域
5. 选鱼漂颜色
6. 勾选`Cordinate`
7. 开始钓鱼。
我自己用的时候是按照这个步骤来的

**Comment by Greetlist** [comment]
@micenote 能用吗？

**Comment by micenote** [comment]
> @micenote 能用吗？

可以用，但成功率不太高。
浮漂有二种状态，有时候那个红色会暗一点。有时候会亮一点。浮漂如果丢的远那个红就偏暗。

**Comment by Greetlist** [comment]
嗯，跟环境关系挺大的，可以找个稳定点的环境，我在瓦德拉肯靠近海象人日常那一片就挺稳定的。也有可能是跟显示器色彩有关系。你那边成功率大概多少？我这边都是在85以上。

**Comment by micenote** [comment]
> 嗯，跟环境关系挺大的，可以找个稳定点的环境，我在瓦德拉肯靠近海象人日常那一片就挺稳定的。也有可能是跟显示器色彩有关系。你那边成功率大概多少？我这边都是在85以上。

大约60%左右。

**Comment by micenote** [comment]
如果钓到海龟，拾取的时候提示要绑定，要点一下确定，现在这个能自动拾取这个东西吗？

**Comment by Greetlist** [comment]
不行，现在没有实现这个点击事件。

**Comment by micenote** [comment]
> 不行，现在没有实现这个点击事件。

我感觉错过了一个亿！

**Comment by Greetlist** [comment]
海龟去要塞搞不是很快么，不一定要在诺森德钓。这个拾取绑定的确认我是没有想到的 😅因为我钓池塘水母跟8.0的鳐鱼没这个问题。这个功能要加我要先调研一下ORC相关的东西了。

**Comment by Greetlist** [comment]
> 海龟去要塞搞不是很快么，不一定要在诺森德钓。这个拾取绑定的确认我是没有想到的 😅因为我钓池塘水母跟8.0的鳐鱼没这个问题。这个功能要加我要先调研一下ORC相关的东西了。

OCR

**Comment by micenote** [comment]
> > 海龟去要塞搞不是很快么，不一定要在诺森德钓。这个拾取绑定的确认我是没有想到的 😅因为我钓池塘水母跟8.0的鳐鱼没这个问题。这个功能要加我要先调研一下ORC相关的东西了。
> 
> OCR

/click StaticPopup1Button1
加个这个宏就可以了

**Comment by Greetlist** [comment]
输入宏命令也可以，感觉总得要加一个判断条件，不可能每一杆都要输入命令一次

**Comment by micenote** [comment]
> 输入宏命令也可以，感觉总得要加一个判断条件，不可能每一杆都要输入命令一次

其实无所谓，每一杆都用一次宏，没有任何影响

**Comment by Greetlist** [comment]
新版本有什么好方法上鱼吗？感觉不在鱼点都是垃圾，剥皮的鱼饵又有点抽象。

**Comment by micenote** [comment]
> 新版本有什么好方法上鱼吗？感觉不在鱼点都是垃圾，剥皮的鱼饵又有点抽象。

哈哈。没啥办法。鱼都不值钱。
感谢作者的辛勤付出。
谢谢。
这个lssues我关了。
祝工作顺利，生活愉快 ：）
