### ISSUE TITLE
雷火的运营是检测你在长时间坐一件事就会封号

### ISSUE THREAD

**Issue by ejys784512** [Greetlist/wow_fishing_script#7]
所以个人感觉你里面的功能跳一跳啊，使用玩具啊其实没用，反正只要你钓鱼时间长了就会被检测

**Comment by Greetlist** [comment]
你被封了么？

**Comment by ejys784512** [comment]
有一个封14天，不过不是用你的软件，用的另一个 图像识别来钓鱼，连续3天上线就钓，然后封号

**Comment by Greetlist** [comment]
这玩意你要赚点小G没人管你，你要动他们的钱那不是没事找事么。对吧？开源的东西，看你自己的用途了。

**Comment by ejys784512** [comment]
是这样的兄弟，现在我换了个号领了14天，又开始钓了，每天不到10小时，一个星期了还没封，不过那个图像识别的软件效率不太高平均1小时250+吧，现在我找这里找各种软件想看看有没有更效率的能到300+的。
感觉图像识别钓鱼的都会有bug影响效率，个人感觉声音识别效率最高，正式服可以设置交互按键完全不需要图像识别，这种脚本可以做的很轻量，逻辑也很简单。
声音阈值判断就行，不用搞什么上钩声音识别
获取了声音就按2个键，延迟做好，继续循环就行。最多就是卡键了，修修bug

**Comment by Greetlist** [comment]
1. 音频的采集跟处理我不知道怎么搞，如果你有这样的想法可以fork出去自己改。
2. 看上鱼的速率，均摊下来的时间差不多就是6-10条/min，250+已经挺好了。我这个没测过，你可以测测。
3. 自用可以，请别商用。虽然我管不着。
